name: run

on:
  workflow_dispatch:
  schedule:
    - cron: '18 10 * * 1'  # every 18:18, Monday
  push:

jobs:
  uploads:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - run: pip install pytz requests icalendar
    - run: |
        python main.py --team 重庆狼队
        python main.py --team 北京WB
        python main.py --team 广州TTG
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: kpl.ics
    #     path: kpl.ics
    - name: commit files
      run: |
        git config --local user.name ${{ github.actor }}
        git status
        git add --force *.ics
        git commit -m "update ics"
        git log
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
