name: run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # every 2:00
  push:

jobs:
  uploads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: pip install -r requirements.txt
      - name: generate ics
        run: |
          rm -f *.ics
          python main.py --team all
          python main.py
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: kpl.ics
      #     path: kpl.ics
      - name: check diff
        id: verify_diff
        run: |
          if [[ -n $(git status --porcelain) ]]; then echo "changed=true" >> $GITHUB_OUTPUT; fi
      - name: commit files
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.name actions-bot
          git status
          git add -A
          git commit -m "update ics"
          git log
      - name: push changes
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
